-- Initialize gym app database
-- This script creates the database and runs all migrations

-- Create database if it doesn't exist
-- Note: This needs to be run as a superuser or database owner
-- CREATE DATABASE gym_app;

-- Connect to the gym_app database
-- \c gym_app;

-- Run all migration files
\i 01_create_users_table.sql
\i 02_create_gym_tables.sql

-- Insert sample data
INSERT INTO gyms (name, address, phone_number, email, description, opening_hours, facilities) VALUES
('FitLife Gym', 'Kadıköy, İstanbul', '+90 216 123 45 67', 'info@fitlifegym.com', 'Modern fitness center with latest equipment', 
 '{"monday": "06:00-23:00", "tuesday": "06:00-23:00", "wednesday": "06:00-23:00", "thursday": "06:00-23:00", "friday": "06:00-23:00", "saturday": "08:00-22:00", "sunday": "08:00-22:00"}',
 '["Cardio Equipment", "Weight Training", "Group Classes", "Personal Training", "Sauna", "Locker Rooms"]'),
('PowerGym', 'Beşiktaş, İstanbul', '+90 212 987 65 43', 'contact@powergym.com', 'Heavy lifting and powerlifting focused gym',
 '{"monday": "05:00-24:00", "tuesday": "05:00-24:00", "wednesday": "05:00-24:00", "thursday": "05:00-24:00", "friday": "05:00-24:00", "saturday": "06:00-23:00", "sunday": "06:00-23:00"}',
 '["Powerlifting Equipment", "Olympic Lifting", "Strongman Equipment", "Cardio", "Locker Rooms"]');

-- Insert all exercises
INSERT INTO workout_exercises (exercise_name, exercise_type, sets, reps, duration, rest_time, notes) VALUES
('Incline Barbell Press', 'Göğüs (Üst)', '4', '6 - 8', '60', '120', 'Ağır yük, kontrollü negatif.'),
('Flat Dumbbell Press', 'Göğüs (Orta)', '3', '8 - 10', '60', '90', 'Tam streç ve pompa.'),
('Seated Dumbbell Press', 'Omuz (Ön)', '3', '8 - 10', '60', '90', 'Omuz gücüne odaklan.'),
('Dumbbell Lateral Raise', 'Omuz (Yan)', '4', '12 - 15', '60', '60', 'Hacim ve izole yanma.'),
('Cable Overhead Extension', 'Triceps (Uzun)', '3', '10 - 12', '60', '60', 'Uzun başı maksimize et.'),
('Rope Triceps Pushdown', 'Triceps (Yan)', '3', '12 - 15', '60', '60', 'Yüksek tekrar ile bitir.'),
('Wide Grip Lat Pulldown / Pull-up', 'Sırt (Genişlik)', '4', '8 - 10', '60', '90', 'Çekişte sırtı kasmaya odaklan.'),
('Barbell Row (Eğilerek)', 'Sırt (Kalınlık)', '3', '8 - 10', '60', '90', 'Kontrollü ve bel desteğiyle.'),
('Single-Arm Dumbbell Row', 'Sırt (Tek Kol)', '3', '8 - 10 (Her Kol)', '60', '75', 'Streç pozisyonu.'),
('Face Pulls', 'Omuz (Arka)', '4', '15 - 20', '60', '60', 'Rotasyon ve omuz sağlığı.'),
('Barbell Curl', 'Biceps (Peak)', '3', '8 - 10', '60', '60', 'Tepe kasılması.'),
('Hammer Curl', 'Biceps (Brachialis)', '3', '10 - 12', '60', '60', 'Ön kol ve kalınlık.'),
('Barbell Back Squat', 'Kuadriseps', '4', '6 - 8', '60', '150', 'Derin ve patlayıcı kalkış.'),
('Romanian Deadlift (RDL)', 'Hamstring', '3', '8 - 10', '60', '120', 'Hamstring strecine odaklan.'),
('Leg Extension', 'Kuadriseps (İzole)', '3', '12 - 15', '60', '60', 'Tepe noktada sıkıştır.'),
('Lying Leg Curl', 'Hamstring (İzole)', '3', '10 - 12', '60', '75', 'Negatif tekrarlara odaklan.'),
('Hip Thrust (Ağırlıklı)', 'Kalça', '3', '8 - 12', '60', '90', 'Kalça kasılması.'),
('Standing Calf Raise', 'Baldır', '4', '12 - 15', '60', '60', 'Maksimum esneme ve kasılma.'),
('Cable Fly (Alttan Üste)', 'Göğüs (Alt)', '3', '12 - 15', '60', '60', 'İzole streç ve kasılma.'),
('Cable Lateral Raise', 'Omuz (Yan)', '3', '15 - 20', '60', '45', 'Yüksek tekrar yanma.'),
('Dumbbell Skullcrusher', 'Triceps (Uzun)', '3', '10 - 12', '60', '60', 'Kolu başın arkasına uzat.'),
('Chest Supported T-Bar Row', 'Sırt (Kalınlık)', '3', '8 - 10', '60', '90', 'Bel desteğiyle saf kalınlık.'),
('Narrow Grip Lat Pulldown', 'Sırt (Genişlik)', '3', '10 - 12', '60', '75', 'Daha derin çekiş.'),
('Incline Dumbbell Curl', 'Biceps', '3', '10 - 12', '60', '60', 'Bicepste tam gerilme.'),
('Leg Press', 'Bacak (Genel)', '3', '10 - 12', '60', '90', 'Yüksek hacimli bileşik hareket.'),
('Seated Leg Curl', 'Hamstring', '3', '12 - 15', '60', '60', 'İzole bitirici.'),
('Hanging Leg Raise', 'Tüm Core', '3', 'Max Tekrar', '60', '60', 'Karın alt bölgesi.'),
('Flat Dumbbell Press', 'Göğüs', '3', '15 - 20', '60', '45', 'Hızlı geçiş.'),
('Cable Fly (Ortadan)', 'Göğüs (İzole)', '3', '15 - 20', '60', '30', 'Süper set yap.'),
('Machine Shoulder Press', 'Omuz (Genel)', '3', '15 - 20', '60', '45', 'Güvenli makine.'),
('Dumbbell Lateral Raise', 'Omuz (Yan)', '3', '20 - 25', '60', '30', 'Yüksek tekrar yanma.'),
('Rope Triceps Pushdown', 'Triceps', '3', '15 - 20', '60', '30', 'Kısa dinlenme.'),
('Lat Pulldown (Orta Tutuş)', 'Sırt (Genişlik)', '3', '15 - 20', '60', '45', 'Tempo yüksek.'),
('Seated Cable Row', 'Sırt (Kalınlık)', '3', '15 - 20', '60', '45', 'Kontrollü hareket.'),
('Machine Reverse Fly', 'Omuz (Arka)', '3', '20 - 25', '60', '30', 'Düşük yük.'),
('Cable Curl', 'Biceps', '3', '15 - 20', '60', '30', 'Hızlı geçiş.'),
('Leg Extension', 'quadriseps', '3', '20 - 25', '60', '45', 'Metabolik stres.'),
('Lying Leg Curl', 'Hamstring', '3', '20 - 25', '60', '45', 'Yüksek tempo.'),
('Glute Bridge (Ağırlıklı)', 'Kalça', '3', '20 - 25', '60', '45', 'Yüksek tekrar.'),
('Standing Calf Raise', 'Baldır', '4', '25 - 30', '60', '30', 'Çok kısa dinlenme.'),
('Incline Dumbbell Press (Hafif)', 'Göğüs (Üst)', '3', '15 - 20', '60', '45', 'nan'),
('Chest Supported Dumbbell Row', 'Sırt (Kalınlık)', '3', '15 - 20', '60', '45', 'nan'),
('Leg Press (Çok Hafif)', 'Bacak', '3', '25 - 30', '60', '45', 'Hacimli yorgunluk.'),
('Incline Dumbbell Press', 'Göğüs (Üst)', '3', '10 - 12', '60', '75', 'Güç koruması.'),
('Pec Deck Fly', 'Göğüs (İzole)', '3', '12 - 15', '60', '60', 'Hafif yük, tam kasılma.'),
('Seated Dumbbell Press', 'Omuz (Ön/Yan)', '3', '10 - 12', '60', '75', 'nan'),
('Cable Lateral Raise', 'Omuz (Yan)', '3', '15 - 20', '60', '60', 'Omuz sağlığına odaklan.'),
('Barbell Row (Hafif)', 'Sırt (Kalınlık)', '3', '10 - 12', '60', '90', 'Teknik öncelikli.'),
('Lat Pulldown', 'Sırt (Genişlik)', '3', '12 - 15', '60', '75', 'nan'),
('Hammer Curl', 'Biceps', '3', '12 - 15', '60', '60', 'nan'),
('Barbell Front Squat / Leg Press', 'Kuadriseps', '3', '10 - 12', '60', '90', 'Orta ağırlık.'),
('Romanian Deadlift (RDL)', 'Hamstring', '3', '10 - 12', '60', '75', 'Streç hisset.'),
('Hanging Leg Raise (Diz Çekme)', 'Tüm Core', '3', '12 - 15', '60', '60', 'nan'),
('Flat Dumbbell Press', 'Göğüs (Orta)', '3', '10 - 12', '60', '75', 'nan'),
('Cable Overhead Extension', 'Triceps', '3', '12 - 15', '60', '60', 'nan'),
('Single-Arm Dumbbell Row', 'Sırt (İzole)', '3', '10 - 12', '60', '75', 'nan'),
('Face Pulls', 'Omuz (Arka)', '3', '15 - 20', '60', '60', 'nan'),
('Leg Extension', 'Kuadriseps', '3', '12 - 15', '60', '60', 'nan'),
('Seated Calf Raise', 'Baldır', '4', '15 - 20', '60', '60', 'nan'),
('Incline Dumbbell Press', 'Göğüs (Üst)', '3', '8 - 12', '60', '90', 'Barbell yerine Dumbbell.'),
('Machine Chest Press', 'Göğüs (Orta)', '3', '10 - 12', '60', '75', 'Makine stabilizasyonu.'),
('Machine Shoulder Press', 'Omuz (Genel)', '3', '10 - 12', '60', '75', 'nan'),
('Dumbbell Lateral Raise', 'Omuz (Yan)', '3', '12 - 15', '60', '60', 'Kontrollü hareket.'),
('Cable Overhead Extension', 'Triceps (Uzun)', '3', '10 - 12', '60', '60', 'nan'),
('Chest Supported Dumbbell Row', 'Sırt (Kalınlık)', '3', '8 - 12', '60', '90', 'Bel desteği ile izole.'),
('Lat Pulldown', 'Sırt (Genişlik)', '3', '10 - 12', '60', '75', 'nan'),
('Face Pulls', 'Omuz (Arka)', '3', '15 - 20', '60', '60', 'nan'),
('Seated Dumbbell Curl', 'Biceps', '3', '10 - 12', '60', '60', 'Oturarak denge sağla.'),
('Leg Press', 'Bacak (Bileşik)', '3', '10 - 15', '60', '120', 'Dizleri zorlama.'),
('Seated Leg Curl', 'Hamstring', '3', '10 - 15', '60', '90', 'İzole.'),
('Leg Extension', 'Kuadriseps (İzole)', '3', '12 - 15', '60', '75', 'nan'),
('Seated Calf Raise', 'Baldır', '4', '12 - 15', '60', '60', 'nan'),
('Cable Fly (Alttan)', 'Göğüs (Alt)', '3', '12 - 15', '60', '60', 'nan'),
('Cable Lateral Raise (İzole)', 'Omuz (Yan/Ön)', '3', '15 - 20', '60', '45', 'nan'),
('Machine Reverse Fly', 'Sırt (İzole)', '3', '15 - 20', '60', '60', 'nan'),
('Hammer Curl', 'Biceps/Ön Kol', '3', '10 - 12', '60', '60', 'nan'),
('Hip Thrust (Hafif Ağırlık)', 'Kalça', '3', '12 - 15', '60', '90', 'nan'),
('Leg Extension (Drop Set)', 'Kuadriseps', '2', '10 + Max', '60', '75', 'nan'),
('Machine Chest Press (Hafif)', 'Göğüs', '3', '12 - 15', '60', '75', 'Kontrollü hareket.'),
('Cable Lateral Raise (Hafif)', 'Omuz (Yan)', '3', '15 - 20', '60', '60', 'Eklem koruması.'),
('Cable Pushdown (Hafif)', 'Triceps', '3', '12 - 15', '60', '60', 'nan'),
('Seated Cable Row', 'Sırt', '3', '12 - 15', '60', '75', 'Oturarak destek al.'),
('Machine Reverse Fly', 'Sırt (İzole)', '3', '15 - 20', '60', '60', 'nan'),
('Seated Dumbbell Curl', 'Biceps', '3', '12 - 15', '60', '60', 'nan'),
('Leg Press (Çok Hafif)', 'Bacak', '3', '15 - 20', '60', '90', 'Düşük yük.'),
('Tek Ayak Üzerinde Durma', 'Denge/CORE', '3', '30 sn (Her Ayak)', '60', '45', 'Mutlaka yapılmalı.'),
('Hafif Yürüyüş ve Esneme', '-', '-', '-', '60', '-', 'nan'),
('Pec Deck Fly', 'Göğüs (İzole)', '3', '12 - 15', '60', '75', 'nan'),
('Side Plank (Yan Karın)', 'CORE', '3', '45 - 60 sn', '60', '60', 'nan'),
('Lat Pulldown (Hafif)', 'Sırt', '3', '12 - 15', '60', '75', 'nan'),
('Bird Dog (Denge ve Core)', 'CORE', '3', '10 (Her Taraf)', '60', '60', 'nan'),
('Leg Extension', 'Kuadriseps', '3', '15 - 20', '60', '60', 'nan'),
('Glute Bridge (Yerden)', 'Kalça', '3', '15 - 20', '60', '60', 'nan'),
('Machine Chest Press', 'Göğüs (Genel)', '3', '15 - 20', '60', '45', 'Makine güvenliği, hızlı tempo.'),
('Dumbbell Fly (Hafif)', 'Göğüs (İzole)', '3', '15 - 20', '60', '30', 'Yüksek tekrar ve yanma.'),
('Machine Shoulder Press', 'Omuz (Genel)', '3', '15 - 20', '60', '45', 'Eklem zorlamasını azalt.'),
('Cable Lateral Raise', 'Omuz (Yan)', '3', '20 - 25', '60', '30', 'Çok kısa dinlenme (Süper Set).'),
('Rope Triceps Pushdown', 'Triceps', '3', '15 - 20', '60', '30', 'İzole bitirici.'),
('Lat Pulldown (Orta Tutuş)', 'Sırt (Genişlik)', '3', '15 - 20', '60', '45', 'Kontrollü iniş.'),
('Seated Cable Row', 'Sırt (Kalınlık)', '3', '15 - 20', '60', '45', 'Yüksek nabızda tut.'),
('Machine Reverse Fly', 'Omuz (Arka)', '3', '20 - 25', '60', '30', 'Düşük yük, yüksek tekrar.'),
('Cable Curl', 'Biceps', '3', '15 - 20', '60', '30', 'Hızlı geçiş.'),
('Leg Extension', 'Kuadriseps', '3', '20 - 25', '60', '45', 'Kan akışını hızlandır.'),
('Lying Leg Curl', 'Hamstring', '3', '20 - 25', '60', '45', 'İzole ve hızlı.'),
('Glute Bridge (Hafif Ağırlık)', 'Kalça', '3', '20 - 25', '60', '45', 'Kalça aktivasyonu.'),
('Seated Calf Raise', 'Baldır', '4', '20 - 25', '60', '30', 'Çok kısa dinlenme (Süper Set).'),
('Dumbbell Press (Hafif)', 'Göğüs/Omuz', '3', '15 - 20', '60', '45', 'Genel güç koruma.'),
('Dumbbell Kickback', 'Triceps', '3', '15 - 20', '60', '30', 'İzole bitirici.'),
('Chest Supported Dumbbell Row', 'Sırt (Kalınlık)', '3', '15 - 20', '60', '45', 'Bel koruması.'),
('Hammer Curl', 'Biceps', '3', '15 - 20', '60', '30', 'Ön kolu da çalıştır.'),
('Leg Press (Çok Hafif)', 'Bacak', '3', '25 - 30', '60', '45', 'Hacimli yorgunluk.'),
('Plank (60 sn) + Russian Twist', 'Tüm Core', '3', 'Max', '60', '45', 'Merkezi stabilite.'),
('Yürüyüş / Eliptik / Bisiklet', '-', '1', '45 - 60 dk', '60', 'Dinlenmesiz', 'nan'),
('Machine Chest Press', 'Göğüs (Genel)', '3', '12 - 15', '60', '75', 'Sırt desteği zorunlu.'),
('Machine Shoulder Press', 'Omuz (Ön/Yan)', '3', '12 - 15', '60', '75', 'Sırt desteği zorunlu.'),
('Cable Lateral Raise (Oturarak)', 'Omuz (Yan/İzole)', '3', '15 - 20', '60', '60', 'Ayakta sallanma yok.'),
('Cable Pushdown (Rope)', 'Triceps', '3', '12 - 15', '60', '60', 'nan'),
('Chest Supported Row (Makine)', 'Sırt (Kalınlık)', '3', '12 - 15', '60', '75', 'Gövde sabitlenmeli.'),
('Lat Pulldown', 'Sırt (Genişlik)', '3', '12 - 15', '60', '75', 'Karın sıkılı olmalı.'),
('Machine Reverse Fly', 'Omuz (Arka)', '3', '15 - 20', '60', '60', 'nan'),
('Cable Curl (Oturarak)', 'Biceps', '3', '12 - 15', '60', '60', 'nan'),
('Leg Press (Yüksek Ayak Poz.)', 'Kuadriseps/Kalça', '3', '12 - 15', '60', '90', 'Alt sırtı mindere bastır.'),
('Seated Leg Curl', 'Hamstring (İzole)', '3', '12 - 15', '60', '75', 'nan'),
('Plank (Dirsek Üstü)', 'CORE (Stabilite)', '3', '45 - 60 sn', '60', '60', 'Omurga için ana hareket.'),
('Cable Fly (Alttan Üste)', 'Göğüs (Üst/Alt)', '3', '15 - 20', '60', '60', 'Göğüsün tüm liflerini izole et.'),
('Dumbbell Lateral Raise (Oturarak)', 'Omuz (Genel)', '3', '15 - 20', '60', '60', 'Yan omuza hacim.'),
('Cable Overhead Extension', 'Triceps (Uzun Baş)', '3', '12 - 15', '60', '60', 'Tricepsi yor.'),
('Bird Dog (Yerden Denge)', 'CORE (Anti-Rotasyon)', '3', '10 - 15 (Her Taraf)', '60', '60', 'Denge ve merkez kuvveti.'),
('Single-Arm Cable Row (Oturarak)', 'Sırt (Tek Kol/İzole)', '3', '12 - 15 (Her Kol)', '60', '75', 'Simetriye odaklan.'),
('Narrow Grip Lat Pulldown', 'Sırt (Genişlik/Ek)', '3', '12 - 15', '60', '75', 'Daha derin çekiş.'),
('Hammer Curl (Oturarak)', 'Biceps (Hacim)', '3', '12 - 15', '60', '60', 'Ön kol gücü ve Biceps kalınlığı.'),
('Face Pulls', 'Omuz (Arka/Tekrar)', '3', '15 - 20', '60', '60', 'Postürü düzelt.'),
('Glute Bridge (Yerden)', 'Kalça (Aktivasyon)', '3', '15 - 20', '60', '60', 'nan'),
('Seated Calf Raise', 'Baldır', '3', '15 - 20', '60', '60', 'nan'),
('Side Plank (Destekli)', 'CORE (Yan)', '3', '30 - 45 sn', '60', '60', 'nan'),
('Flat Dumbbell Press', 'Göğüs (Genel)', '3', '10 - 15', '60', '75', 'Yatarak yapılır.'),
('Machine Shoulder Press', 'Omuz (Genel)', '3', '12 - 15', '60', '75', 'Sırt desteği şart.'),
('Cable Lateral Raise (Oturarak)', 'Omuz (Yan/Hacim)', '3', '15 - 20', '60', '60', 'Yüksek tekrar ile yanma hissi.'),
('Cable Overhead Extension', 'Triceps (Uzun Baş)', '3', '12 - 15', '60', '60', 'nan'),
('Chest Supported Row', 'Sırt (Kalınlık)', '3', '10 - 15', '60', '75', 'Gövdeyi sabitle.'),
('Lat Pulldown', 'Sırt (Genişlik)', '3', '10 - 15', '60', '75', 'nan'),
('Machine Reverse Fly', 'Omuz (Arka)', '3', '15 - 20', '60', '60', 'nan'),
('Seated Dumbbell Curl', 'Biceps', '3', '12 - 15', '60', '60', 'Oturarak destek al.'),
('Leg Extension', 'Kuadriseps', '4', '15 - 20', '60', '60', 'Ağırlık ÇOK HAFİF, yavaş tempo (3 sn indiriş).'),
('Seated Leg Curl', 'Hamstring', '4', '15 - 20', '60', '60', 'Diz arkasını zorlama.'),
('Glute Bridge (Yerden)', 'Kalça (İzole)', '3', '15 - 20', '60', '60', 'nan'),
('Plank (Dirsek Üstü)', 'CORE', '3', '60 sn', '60', '60', 'nan'),
('Cable Fly (Ortadan)', 'Göğüs (Üst/Alt)', '3', '15 - 20', '60', '60', 'Göğüsün dış liflerini izole et.'),
('Cable Lateral Raise (Ayakta)', 'Omuz (Yan/Tekrar)', '3', '15 - 20', '60', '45', 'Omuz eklemini ısıt.'),
('Rope Triceps Pushdown', 'Triceps (Yan Baş)', '3', '12 - 15', '60', '60', 'Maksimum kasılma.'),
('Dumbbell Front Raise', 'Omuz (Ön/İzole)', '3', '12 - 15', '60', '60', 'Hafif ağırlıkla.'),
('Single-Arm Cable Row', 'Sırt (Tek Kol)', '3', '12 - 15 (Her Kol)', '60', '75', 'Simetriye odaklan.'),
('Narrow Grip Lat Pulldown', 'Sırt (Genişlik/Ek)', '3', '12 - 15', '60', '75', 'Sırtın alt kısmına odaklan.'),
('Incline Dumbbell Curl (Hafif)', 'Biceps (Streç)', '3', '12 - 15', '60', '60', 'Oturarak denge sağla.'),
('Face Pulls', 'Omuz (Arka/Postür)', '3', '15 - 20', '60', '60', 'Postürü düzelt.'),
('Cable Hip Abduction', 'Kalça (Aktivasyon)', '3', '15 - 20 (Her Bacak)', '60', '60', 'Diz eklemini stabilize eden kalça kaslarını güçlendir.'),
('Seated Calf Raise', 'Baldır', '3', '15 - 20', '60', '60', 'nan'),
('Side Plank', 'CORE (Yan)', '3', '45 - 60 sn', '60', '60', 'nan'),
('Seated Dumbbell Press (Hafif)', 'Omuz (Genel)', '3', '12 - 15', '60', '90', 'nan'),
('Cable Lateral Raise (Hafif)', 'Omuz (Yan/Hacim)', '3', '15 - 20', '60', '75', 'nan'),
('Cable Overhead Extension', 'Triceps (Uzun Baş)', '3', '12 - 15', '60', '75', 'nan'),
('Seated Cable Row', 'Sırt (Kalınlık)', '3', '12 - 15', '60', '90', 'nan'),
('Lat Pulldown', 'Sırt (Genişlik)', '3', '12 - 15', '60', '90', 'nan'),
('Machine Reverse Fly', 'Omuz (Arka)', '3', '12 - 15', '60', '75', 'nan'),
('Dumbbell Curl (Oturarak)', 'Biceps', '3', '12 - 15', '60', '75', 'nan'),
('Leg Extension', 'Kuadriseps', '3', '12 - 15', '60', '90', 'nan'),
('Seated Leg Curl', 'Hamstring', '3', '12 - 15', '60', '90', 'nan'),
('Glute Bridge (Yerden)', 'Kalça', '3', '15 - 20', '60', '75', 'İzometrik tutma süresi kısa olmalı.'),
('Eliptik / Bisiklet (Hafif)', 'Ana Kardiyo', '1', '30 - 45 dk', '60', '-', 'Nabız kontrol edilmeli.'),
('Pec Deck Fly', 'Göğüs (İzole)', '3', '12 - 15', '60', '75', 'Hacim ve pompa.'),
('Dumbbell Lateral Raise (Süper Set YOK)', 'Omuz (Ön/Yan)', '3', '15 - 20', '60', '75', 'Her set arası dinlen.'),
('Rope Triceps Pushdown', 'Triceps (Yan Baş)', '3', '12 - 15', '60', '75', 'nan'),
('Cable Woodchopper (Yukarıdan)', 'CORE (Dinamik)', '3', '12 - 15', '60', '75', 'Dinamik CORE hareketleri.'),
('Single-Arm Cable Row', 'Sırt (Tek Kol)', '3', '12 - 15 (Her Kol)', '60', '75', 'nan'),
('Narrow Grip Lat Pulldown', 'Sırt (Ekstra)', '3', '12 - 15', '60', '75', 'nan'),
('Cable Curl', 'Biceps (İzole)', '3', '12 - 15', '60', '75', 'nan'),
('Face Pulls', 'Omuz (Arka)', '3', '15 - 20', '60', '75', 'nan'),
('Seated Calf Raise', 'Baldır', '3', '15 - 20', '60', '60', 'nan'),
('Dynamic Crunch (Yerden Kısa)', 'CORE (Dinamik)', '3', '15 - 20', '60', '60', 'nan');

-- Insert all diets (TODO)

-- Create a function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_gyms_updated_at BEFORE UPDATE ON gyms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_memberships_updated_at BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_workouts_updated_at BEFORE UPDATE ON workouts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Grant permissions (adjust as needed for your setup)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gym_app_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO gym_app_user;
